export const ADMIN_GET_ALL_ALLOWANCES_REQUEST =
  "ADMIN_GET_ALL_ALLOWANCES_REQUEST";
export const ADMIN_GET_ALL_ALLOWANCES_SUCCESS =
  "ADMIN_GET_ALL_ALLOWANCES_SUCCESS";
export const ADMIN_GET_ALL_ALLOWANCES_FAIL = "ADMIN_GET_ALL_ALLOWANCES_FAIL";
export const ADMIN_GET_ALL_ALLOWANCES_RESET = "ADMIN_GET_ALL_ALLOWANCES_RESET";

export const ADMIN_CREATE_ALLOWANCE_REQUEST = "ADMIN_CREATE_ALLOWANCE_REQUEST";
export const ADMIN_CREATE_ALLOWANCE_SUCCESS = "ADMIN_CREATE_ALLOWANCE_SUCCESS";
export const ADMIN_CREATE_ALLOWANCE_FAIL = "ADMIN_CREATE_ALLOWANCE_FAIL";
export const ADMIN_CREATE_ALLOWANCE_RESET = "ADMIN_CREATE_ALLOWANCE_RESET";

export const ADMIN_UPDATE_ALLOWANCE_BY_ID_REQUEST =
  "ADMIN_UPDATE_ALLOWANCE_BY_ID_REQUEST";
export const ADMIN_UPDATE_ALLOWANCE_BY_ID_SUCCESS =
  "ADMIN_UPDATE_ALLOWANCE_BY_ID_SUCCESS";
export const ADMIN_UPDATE_ALLOWANCE_BY_ID_FAIL =
  "ADMIN_UPDATE_ALLOWANCE_BY_ID_FAIL";
export const ADMIN_UPDATE_ALLOWANCE_BY_ID_RESET =
  "ADMIN_UPDATE_ALLOWANCE_BY_ID_RESET";

export const ADMIN_DELETE_ALLOWANCE_BY_ID_REQUEST =
  "ADMIN_DELETE_ALLOWANCE_BY_ID_REQUEST";
export const ADMIN_DELETE_ALLOWANCE_BY_ID_SUCCESS =
  "ADMIN_DELETE_ALLOWANCE_BY_ID_SUCCESS";
export const ADMIN_DELETE_ALLOWANCE_BY_ID_FAIL =
  "ADMIN_DELETE_ALLOWANCE_BY_ID_FAIL";
export const ADMIN_DELETE_ALLOWANCE_BY_ID_RESET =
  "ADMIN_DELETE_ALLOWANCE_BY_ID_RESET";
