export const LOGIN_ADMIN_USER_REQUEST = "LOGIN_ADMIN_USER_REQUEST";
export const LOGIN_ADMIN_USER_SUCCESS = "LOGIN_ADMIN_USER_SUCCESS";
export const LOGIN_ADMIN_USER_FAIL = "LOGIN_ADMIN_USER_FAIL";
export const LOGIN_ADMIN_USER_RESET = "LOGIN_ADMIN_USER_RESET";

export const CHECK_ADMIN_LOGIN_STATUS_REQUEST =
  "CHECK_ADMIN_LOGIN_STATUS_REQUEST";
export const CHECK_ADMIN_LOGIN_STATUS_SUCCESS =
  "CHECK_ADMIN_LOGIN_STATUS_SUCCESS";
export const CHECK_ADMIN_LOGIN_STATUS_FAIL = "CHECK_ADMIN_LOGIN_STATUS_FAIL";

export const CHECK_COOKIE_TOKEN_VALID_REQUEST =
  "CHECK_COOKIE_TOKEN_VALID_REQUEST";
export const CHECK_COOKIE_TOKEN_VALID_SUCCESS =
  "CHECK_COOKIE_TOKEN_VALID_SUCCESS";
export const CHECK_COOKIE_TOKEN_VALID_FAIL = "CHECK_COOKIE_TOKEN_VALID_FAIL";
export const CHECK_COOKIE_TOKEN_VALID_RESET = "CHECK_COOKIE_TOKEN_VALID_RESET";

export const ADMIN_LOGGEDIN_DETAILS_REQUEST = "ADMIN_LOGGEDIN_DETAILS_REQUEST";
export const ADMIN_LOGGEDIN_DETAILS_SUCCESS = "ADMIN_LOGGEDIN_DETAILS_SUCCESS";
export const ADMIN_LOGGEDIN_DETAILS_FAIL = "ADMIN_LOGGEDIN_DETAILS_FAIL";
export const ADMIN_LOGGEDIN_DETAILS_RESET = "ADMIN_LOGGEDIN_DETAILS_RESET";

export const ADMIN_UPDATE_LOGGEDIN_DETAILS_REQUEST =
  "ADMIN_UPDATE_LOGGEDIN_DETAILS_REQUEST";
export const ADMIN_UPDATE_LOGGEDIN_DETAILS_SUCCESS =
  "ADMIN_UPDATE_LOGGEDIN_DETAILS_SUCCESS";
export const ADMIN_UPDATE_LOGGEDIN_DETAILS_FAIL =
  "ADMIN_UPDATE_LOGGEDIN_DETAILS_FAIL";
export const ADMIN_UPDATE_LOGGEDIN_DETAILS_RESET =
  "ADMIN_UPDATE_LOGGEDIN_DETAILS_RESET";

export const ADMIN_FORGOT_PASSWORD_REQUEST = "ADMIN_FORGOT_PASSWORD_REQUEST";
export const ADMIN_FORGOT_PASSWORD_SUCCESS = "ADMIN_FORGOT_PASSWORD_SUCCESS";
export const ADMIN_FORGOT_PASSWORD_FAIL = "ADMIN_FORGOT_PASSWORD_FAIL";
export const ADMIN_FORGOT_PASSWORD_RESET = "ADMIN_FORGOT_PASSWORD_RESET";

export const ADMIN_RESET_PASSWORD_REQUEST = "ADMIN_RESET_PASSWORD_REQUEST";
export const ADMIN_RESET_PASSWORD_SUCCESS = "ADMIN_RESET_PASSWORD_SUCCESS";
export const ADMIN_RESET_PASSWORD_FAIL = "ADMIN_RESET_PASSWORD_FAIL";
export const ADMIN_RESET_PASSWORD_RESET = "ADMIN_RESET_PASSWORD_RESET";

export const CEO_UPLOAD_SIGNATURE_IMAGE_REQUEST =
  "CEO_UPLOAD_SIGNATURE_IMAGE_REQUEST";
export const CEO_UPLOAD_SIGNATURE_IMAGE_SUCCESS =
  "CEO_UPLOAD_SIGNATURE_IMAGE_SUCCESS";
export const CEO_UPLOAD_SIGNATURE_IMAGE_FAIL =
  "CEO_UPLOAD_SIGNATURE_IMAGE_FAIL";
export const CEO_UPLOAD_SIGNATURE_IMAGE_RESET =
  "CEO_UPLOAD_SIGNATURE_IMAGE_RESET";

export const LOGOUT_ADMIN_USER = "LOGOUT_ADMIN_USER";
