export const GET_ALL_BANK_NAMES_REQUEST = "GET_ALL_BANK_NAMES_REQUEST";
export const GET_ALL_BANK_NAMES_SUCCESS = "GET_ALL_BANK_NAMES_SUCCESS";
export const GET_ALL_BANK_NAMES_FAIL = "GET_ALL_BANK_NAMES_FAIL";

export const GET_ALL_BANK_LISTS_REQUEST = "GET_ALL_BANK_LISTS_REQUEST";
export const GET_ALL_BANK_LISTS_SUCCESS = "GET_ALL_BANK_LISTS_SUCCESS";
export const GET_ALL_BANK_LISTS_FAIL = "GET_ALL_BANK_LISTS_FAIL";

export const ACCOUNTANT_CREATE_BANK_REQUEST = "ACCOUNTANT_CREATE_BANK_REQUEST";
export const ACCOUNTANT_CREATE_BANK_SUCCESS = "ACCOUNTANT_CREATE_BANK_SUCCESS";
export const ACCOUNTANT_CREATE_BANK_FAIL = "ACCOUNTANT_CREATE_BANK_FAIL";
export const ACCOUNTANT_CREATE_BANK_RESET = "ACCOUNTANT_CREATE_BANK_RESET";

export const ACCOUNTANT_UPDATE_BANK_BY_ID_REQUEST =
  "ACCOUNTANT_UPDATE_BANK_BY_ID_REQUEST";
export const ACCOUNTANT_UPDATE_BANK_BY_ID_SUCCESS =
  "ACCOUNTANT_UPDATE_BANK_BY_ID_SUCCESS";
export const ACCOUNTANT_UPDATE_BANK_BY_ID_FAIL =
  "ACCOUNTANT_UPDATE_BANK_BY_ID_FAIL";
export const ACCOUNTANT_UPDATE_BANK_BY_ID_RESET =
  "ACCOUNTANT_UPDATE_BANK_BY_ID_RESET";
