export const ACCOUNTANT_CREATE_BANKSCHEDULE_REQUEST =
  "ACCOUNTANT_CREATE_BANKSCHEDULE_REQUEST";
export const ACCOUNTANT_CREATE_BANKSCHEDULE_SUCCESS =
  "ACCOUNTANT_CREATE_BANKSCHEDULE_SUCCESS";
export const ACCOUNTANT_CREATE_BANKSCHEDULE_FAIL =
  "ACCOUNTANT_CREATE_BANKSCHEDULE_FAIL";
export const ACCOUNTANT_CREATE_BANKSCHEDULE_RESET =
  "ACCOUNTANT_CREATE_BANKSCHEDULE_RESET";

export const ACCOUNTANT_GET_MONTHLY_BANKSCHEDULE_REQUEST =
  "ACCOUNTANT_GET_MONTHLY_BANKSCHEDULE_REQUEST";
export const ACCOUNTANT_GET_MONTHLY_BANKSCHEDULE_SUCCESS =
  "ACCOUNTANT_GET_MONTHLY_BANKSCHEDULE_SUCCESS";
export const ACCOUNTANT_GET_MONTHLY_BANKSCHEDULE_FAIL =
  "ACCOUNTANT_GET_MONTHLY_BANKSCHEDULE_FAIL";

export const ACCOUNTANT_DELETE_BANKSCHEDULE_BY_ID_REQUEST =
  "ACCOUNTANT_DELETE_BANKSCHEDULE_BY_ID_REQUEST";
export const ACCOUNTANT_DELETE_BANKSCHEDULE_BY_ID_SUCCESS =
  "ACCOUNTANT_DELETE_BANKSCHEDULE_BY_ID_SUCCESS";
export const ACCOUNTANT_DELETE_BANKSCHEDULE_BY_ID_FAIL =
  "ACCOUNTANT_DELETE_BANKSCHEDULE_BY_ID_FAIL";
export const ACCOUNTANT_DELETE_BANKSCHEDULE_BY_ID_RESET =
  "ACCOUNTANT_DELETE_BANKSCHEDULE_BY_ID_RESET";

export const ACCOUNTANT_GET_APPROVED_BANKSCHEDULE_VOUCHERS_REQUEST =
  "ACCOUNTANT_GET_APPROVED_BANKSCHEDULE_VOUCHERS_REQUEST";
export const ACCOUNTANT_GET_APPROVED_BANKSCHEDULE_VOUCHERS_SUCCESS =
  "ACCOUNTANT_GET_APPROVED_BANKSCHEDULE_VOUCHERS_SUCCESS";
export const ACCOUNTANT_GET_APPROVED_BANKSCHEDULE_VOUCHERS_FAIL =
  "ACCOUNTANT_GET_APPROVED_BANKSCHEDULE_VOUCHERS_FAIL";

export const CEO_GET_NOT_APPROVED_BANKSCHEDULES_REQUEST =
  "CEO_GET_NOT_APPROVED_BANKSCHEDULES_REQUEST";
export const CEO_GET_NOT_APPROVED_BANKSCHEDULES_SUCCESS =
  "CEO_GET_NOT_APPROVED_BANKSCHEDULES_SUCCESS";
export const CEO_GET_NOT_APPROVED_BANKSCHEDULES_FAIL =
  "CEO_GET_NOT_APPROVED_BANKSCHEDULES_FAIL";
export const CEO_GET_NOT_APPROVED_BANKSCHEDULES_RESET =
  "CEO_GET_NOT_APPROVED_BANKSCHEDULES_RESET";

export const CEO_APPROVE_BANKSCHEDULES_REQUEST =
  "CEO_APPROVE_BANKSCHEDULES_REQUEST";
export const CEO_APPROVE_BANKSCHEDULES_SUCCESS =
  "CEO_APPROVE_BANKSCHEDULES_SUCCESS";
export const CEO_APPROVE_BANKSCHEDULES_FAIL = "CEO_APPROVE_BANKSCHEDULES_FAIL";
export const CEO_APPROVE_BANKSCHEDULES_RESET =
  "CEO_APPROVE_BANKSCHEDULES_RESET";
