export const HR_GET_BASEPAY_REQUEST = "HR_GET_BASEPAY_REQUEST";
export const HR_GET_BASEPAY_SUCCESS = "HR_GET_BASEPAY_SUCCESS";
export const HR_GET_BASEPAY_FAIL = "HR_GET_BASEPAY_FAIL";
// export const HR_GET_BASEPAY_RESET = "HR_GET_BASEPAY_RESET";

export const HR_CREATE_BASEPAY_REQUEST = "HR_CREATE_BASEPAY_REQUEST";
export const HR_CREATE_BASEPAY_SUCCESS = "HR_CREATE_BASEPAY_SUCCESS";
export const HR_CREATE_BASEPAY_FAIL = "HR_CREATE_BASEPAY_FAIL";
export const HR_CREATE_BASEPAY_RESET = "HR_CREATE_BASEPAY_RESET";

export const HR_UPDATE_BASEPAY_BY_ID_REQUEST =
  "HR_UPDATE_BASEPAY_BY_ID_REQUEST";
export const HR_UPDATE_BASEPAY_BY_ID_SUCCESS =
  "HR_UPDATE_BASEPAY_BY_ID_SUCCESS";
export const HR_UPDATE_BASEPAY_BY_ID_FAIL = "HR_UPDATE_BASEPAY_BY_ID_FAIL";
export const HR_UPDATE_BASEPAY_BY_ID_RESET = "HR_UPDATE_BASEPAY_BY_ID_RESET";
