export const GET_DASHBOARD_REPORTS_RESULT_REQUEST =
  "GET_DASHBOARD_REPORTS_RESULT_REQUEST";
export const GET_DASHBOARD_REPORTS_RESULT_SUCCESS =
  "GET_DASHBOARD_REPORTS_RESULT_SUCCESS";
export const GET_DASHBOARD_REPORTS_RESULT_FAIL =
  "GET_DASHBOARD_REPORTS_RESULT_FAIL";
