export const ADMIN_GET_ALL_DEDUCTIONS_REQUEST =
  "ADMIN_GET_ALL_DEDUCTIONS_REQUEST";
export const ADMIN_GET_ALL_DEDUCTIONS_SUCCESS =
  "ADMIN_GET_ALL_DEDUCTIONS_SUCCESS";
export const ADMIN_GET_ALL_DEDUCTIONS_FAIL = "ADMIN_GET_ALL_DEDUCTIONS_FAIL";
export const ADMIN_GET_ALL_DEDUCTIONS_RESET = "ADMIN_GET_ALL_DEDUCTIONS_RESET";

export const ADMIN_CREATE_DEDUCTION_REQUEST = "ADMIN_CREATE_DEDUCTION_REQUEST";
export const ADMIN_CREATE_DEDUCTION_SUCCESS = "ADMIN_CREATE_DEDUCTION_SUCCESS";
export const ADMIN_CREATE_DEDUCTION_FAIL = "ADMIN_CREATE_DEDUCTION_FAIL";
export const ADMIN_CREATE_DEDUCTION_RESET = "ADMIN_CREATE_DEDUCTION_RESET";

export const ADMIN_UPDATE_DEDUCTION_BY_ID_REQUEST =
  "ADMIN_UPDATE_DEDUCTION_BY_ID_REQUEST";
export const ADMIN_UPDATE_DEDUCTION_BY_ID_SUCCESS =
  "ADMIN_UPDATE_DEDUCTION_BY_ID_SUCCESS";
export const ADMIN_UPDATE_DEDUCTION_BY_ID_FAIL =
  "ADMIN_UPDATE_DEDUCTION_BY_ID_FAIL";
export const ADMIN_UPDATE_DEDUCTION_BY_ID_RESET =
  "ADMIN_UPDATE_DEDUCTION_BY_ID_RESET";

export const ADMIN_DELETE_DEDUCTION_BY_ID_REQUEST =
  "ADMIN_DELETE_DEDUCTION_BY_ID_REQUEST";
export const ADMIN_DELETE_DEDUCTION_BY_ID_SUCCESS =
  "ADMIN_DELETE_DEDUCTION_BY_ID_SUCCESS";
export const ADMIN_DELETE_DEDUCTION_BY_ID_FAIL =
  "ADMIN_DELETE_DEDUCTION_BY_ID_FAIL";
export const ADMIN_DELETE_DEDUCTION_BY_ID_RESET =
  "ADMIN_DELETE_ALLOWANCE_BY_ID_RESET";
