export const GET_ALL_DEPARTMENTS_REQUEST = "GET_ALL_DEPARTMENTS_REQUEST";
export const GET_ALL_DEPARTMENTS_SUCCESS = "GET_ALL_DEPARTMENTS_SUCCESS";
export const GET_ALL_DEPARTMENTS_FAIL = "GET_ALL_DEPARTMENTS_FAIL";
export const GET_ALL_DEPARTMENTS_RESET = "GET_ALL_DEPARTMENTS_RESET";

export const GET_POSITION_BY_DEPARTMENT_REQUEST =
  "GET_POSITION_BY_DEPARTMENT_REQUEST";
export const GET_POSITION_BY_DEPARTMENT_SUCCESS =
  "GET_POSITION_BY_DEPARTMENT_SUCCESS";
export const GET_POSITION_BY_DEPARTMENT_FAIL =
  "GET_POSITION_BY_DEPARTMENT_FAIL";
export const GET_POSITION_BY_DEPARTMENT_RESET =
  "GET_POSITION_BY_DEPARTMENT_RESET";

export const ADMIN_CREATE_DEPARTMENT_REQUEST =
  "ADMIN_CREATE_DEPARTMENT_REQUEST";
export const ADMIN_CREATE_DEPARTMENT_SUCCESS =
  "ADMIN_CREATE_DEPARTMENT_SUCCESS";
export const ADMIN_CREATE_DEPARTMENT_FAIL = "ADMIN_CREATE_DEPARTMENT_FAIL";
export const ADMIN_CREATE_DEPARTMENT_RESET = "ADMIN_CREATE_DEPARTMENT_RESET";

export const ADMIN_UPDATE_DEPARTMENT_BY_ID_REQUEST =
  "ADMIN_UPDATE_DEPARTMENT_BY_ID_REQUEST";
export const ADMIN_UPDATE_DEPARTMENT_BY_ID_SUCCESS =
  "ADMIN_UPDATE_DEPARTMENT_BY_ID_SUCCESS";
export const ADMIN_UPDATE_DEPARTMENT_BY_ID_FAIL =
  "ADMIN_UPDATE_DEPARTMENT_BY_ID_FAIL";
export const ADMIN_UPDATE_DEPARTMENT_BY_ID_RESET =
  "ADMIN_UPDATE_DEPARTMENT_BY_ID_RESET";

export const ADMIN_DELETE_DEPARTMENT_BY_ID_REQUEST =
  "ADMIN_DELETE_DEPARTMENT_BY_ID_REQUEST";
export const ADMIN_DELETE_DEPARTMENT_BY_ID_SUCCESS =
  "ADMIN_DELETE_DEPARTMENT_BY_ID_SUCCESS";
export const ADMIN_DELETE_DEPARTMENT_BY_ID_FAIL =
  "ADMIN_DELETE_DEPARTMENT_BY_ID_FAIL";
export const ADMIN_DELETE_DEPARTMENT_BY_ID_RESET =
  "ADMIN_DELETE_DEPARTMENT_BY_ID_RESET";
