export const DOWNLOADING_ON_PROCESS_REQUEST = "DOWNLOADING_ON_PROCESS_REQUEST";
export const DOWNLOADING_ON_PROCESS_DONE = "DOWNLOADING_ON_PROCESS_DONE";
export const DOWNLOADING_ON_PROCESS_ERROR = "DOWNLOADING_ON_PROCESS_ERROR";
export const DOWNLOADING_ON_PROCESS_RESET = "DOWNLOADING_ON_PROCESS_RESET";
