export const ADMIN_CREATE_EMPLOYEE_REQUEST = "ADMIN_CREATE_EMPLOYEE_REQUEST";
export const ADMIN_CREATE_EMPLOYEE_SUCCESS = "ADMIN_CREATE_EMPLOYEE_SUCCESS";
export const ADMIN_CREATE_EMPLOYEE_FAIL = "ADMIN_CREATE_EMPLOYEE_FAIL";
export const ADMIN_CREATE_EMPLOYEE_RESET = "ADMIN_CREATE_EMPLOYEE_RESET";

export const HR_UPLOAD_CONTRACT_EMPLOYEE_REQUEST =
  "HR_UPLOAD_CONTRACT_EMPLOYEE_REQUEST";
export const HR_UPLOAD_CONTRACT_EMPLOYEE_SUCCESS =
  "HR_UPLOAD_CONTRACT_EMPLOYEE_SUCCESS";
export const HR_UPLOAD_CONTRACT_EMPLOYEE_FAIL =
  "HR_UPLOAD_CONTRACT_EMPLOYEE_FAIL";
export const HR_UPLOAD_CONTRACT_EMPLOYEE_RESET =
  "HR_UPLOAD_CONTRACT_EMPLOYEE_RESET";

export const ADMIN_CREATE_BULK_EMPLOYEE_REQUEST =
  "ADMIN_CREATE_BULK_EMPLOYEE_REQUEST";
export const ADMIN_CREATE_BULK_EMPLOYEE_SUCCESS =
  "ADMIN_CREATE_BULK_EMPLOYEE_SUCCESS";
export const ADMIN_CREATE_BULK_EMPLOYEE_FAIL =
  "ADMIN_CREATE_BULK_EMPLOYEE_FAIL";
export const ADMIN_CREATE_BULK_EMPLOYEE_RESET =
  "ADMIN_CREATE_BULK_EMPLOYEE_RESET";

export const ADMIN_CREATE_BULK_EMPLOYEE_ALL_REQUEST =
  "ADMIN_CREATE_BULK_EMPLOYEE_ALL_REQUEST";
export const ADMIN_CREATE_BULK_EMPLOYEE_ALL_SUCCESS =
  "ADMIN_CREATE_BULK_EMPLOYEE_ALL_SUCCESS";
export const ADMIN_CREATE_BULK_EMPLOYEE_ALL_FAIL =
  "ADMIN_CREATE_BULK_EMPLOYEE_ALL_FAIL";
export const ADMIN_CREATE_BULK_EMPLOYEE_ALL_RESET =
  "ADMIN_CREATE_BULK_EMPLOYEE_ALL_RESET";

export const ADMIN_CREATE_BULK_EMPLOYEE_FILE_REQUEST =
  "ADMIN_CREATE_BULK_EMPLOYEE_FILE_REQUEST";
export const ADMIN_CREATE_BULK_EMPLOYEE_FILE_SUCCESS =
  "ADMIN_CREATE_BULK_EMPLOYEE_FILE_SUCCESS";
export const ADMIN_CREATE_BULK_EMPLOYEE_FILE_FAIL =
  "ADMIN_CREATE_BULK_EMPLOYEE_FILE_FAIL";
export const ADMIN_CREATE_BULK_EMPLOYEE_FILE_RESET =
  "ADMIN_CREATE_BULK_EMPLOYEE_FILE_RESET";

export const ADMIN_GET_ALL_EMPLOYEE_REQUEST = "ADMIN_GET_ALL_EMPLOYEE_REQUEST";
export const ADMIN_GET_ALL_EMPLOYEE_SUCCESS = "ADMIN_GET_ALL_EMPLOYEE_SUCCESS";
export const ADMIN_GET_ALL_EMPLOYEE_FAIL = "ADMIN_GET_ALL_EMPLOYEE_FAIL";
export const ADMIN_GET_ALL_EMPLOYEE_RESET = "ADMIN_GET_ALL_EMPLOYEE_RESET";

export const ADMIN_UPDATE_EMPLOYEE_BY_ID_REQUEST =
  "ADMIN_UPDATE_EMPLOYEE_BY_ID_REQUEST";
export const ADMIN_UPDATE_EMPLOYEE_BY_ID_SUCCESS =
  "ADMIN_UPDATE_EMPLOYEE_BY_ID_SUCCESS";
export const ADMIN_UPDATE_EMPLOYEE_BY_ID_FAIL =
  "ADMIN_UPDATE_EMPLOYEE_BY_ID_FAIL";
export const ADMIN_UPDATE_EMPLOYEE_BY_ID_RESET =
  "ADMIN_UPDATE_EMPLOYEE_BY_ID_RESET";

export const ADMIN_DELETE_EMPLOYEE_BY_ID_REQUEST =
  "ADMIN_DELETE_EMPLOYEE_BY_ID_REQUEST";
export const ADMIN_DELETE_EMPLOYEE_BY_ID_SUCCESS =
  "ADMIN_DELETE_EMPLOYEE_BY_ID_SUCCESS";
export const ADMIN_DELETE_EMPLOYEE_BY_ID_FAIL =
  "ADMIN_DELETE_EMPLOYEE_BY_ID_FAIL";
export const ADMIN_DELETE_EMPLOYEE_BY_ID_RESET =
  "ADMIN_DELETE_EMPLOYEE_BY_ID_RESET";

export const ADMIN_EMPLOYEE_TOPUP_REQUEST = "ADMIN_EMPLOYEE_TOPUP_REQUEST";
export const ADMIN_EMPLOYEE_TOPUP_SUCCESS = "ADMIN_EMPLOYEE_TOPUP_SUCCESS";
export const ADMIN_EMPLOYEE_TOPUP_FAIL = "ADMIN_EMPLOYEE_TOPUP_FAIL";
export const ADMIN_EMPLOYEE_TOPUP_RESET = "ADMIN_EMPLOYEE_TOPUP_RESET";

export const ADMIN_DELETE_EMPLOYEE_ALLOWANCE_BY_ID_REQUEST =
  "ADMIN_DELETE_EMPLOYEE_ALLOWANCE_BY_ID_REQUEST";
export const ADMIN_DELETE_EMPLOYEE_ALLOWANCE_BY_ID_SUCCESS =
  "ADMIN_DELETE_EMPLOYEE_ALLOWANCE_BY_ID_SUCCESS";
export const ADMIN_DELETE_EMPLOYEE_ALLOWANCE_BY_ID_FAIL =
  "ADMIN_DELETE_EMPLOYEE_ALLOWANCE_BY_ID_FAIL";
export const ADMIN_DELETE_EMPLOYEE_ALLOWANCE_BY_ID_RESET =
  "ADMIN_DELETE_EMPLOYEE_ALLOWANCE_BY_ID_RESET";

export const ADMIN_DELETE_EMPLOYEE_DEDUCTION_BY_ID_REQUEST =
  "ADMIN_DELETE_EMPLOYEE_DEDUCTION_BY_ID_REQUEST";
export const ADMIN_DELETE_EMPLOYEE_DEDUCTION_BY_ID_SUCCESS =
  "ADMIN_DELETE_EMPLOYEE_DEDUCTION_BY_ID_SUCCESS";
export const ADMIN_DELETE_EMPLOYEE_DEDUCTION_BY_ID_FAIL =
  "ADMIN_DELETE_EMPLOYEE_DEDUCTION_BY_ID_FAIL";
export const ADMIN_DELETE_EMPLOYEE_DEDUCTION_BY_ID_RESET =
  "ADMIN_DELETE_EMPLOYEE_DEDUCTION_BY_ID_RESET";

export const ADMIN_DELETE_BULK_EMPLOYEES_BY_IDS_REQUEST =
  "ADMIN_DELETE_BULK_EMPLOYEES_BY_IDS_REQUEST";
export const ADMIN_DELETE_BULK_EMPLOYEES_BY_IDS_SUCCESS =
  "ADMIN_DELETE_BULK_EMPLOYEES_BY_IDS_SUCCESS";
export const ADMIN_DELETE_BULK_EMPLOYEES_BY_IDS_FAIL =
  "ADMIN_DELETE_BULK_EMPLOYEES_BY_IDS_FAIL";
export const ADMIN_DELETE_BULK_EMPLOYEES_BY_IDS_RESET =
  "ADMIN_DELETE_BULK_EMPLOYEES_BY_IDS_RESET";

export const ADMIN_DELETE_ALL_EMPLOYEES_REQUEST =
  "ADMIN_DELETE_ALL_EMPLOYEES_REQUEST";
export const ADMIN_DELETE_ALL_EMPLOYEES_SUCCESS =
  "ADMIN_DELETE_ALL_EMPLOYEES_SUCCESS";
export const ADMIN_DELETE_ALL_EMPLOYEES_FAIL =
  "ADMIN_DELETE_ALL_EMPLOYEES_FAIL";
export const ADMIN_DELETE_ALL_EMPLOYEES_RESET =
  "ADMIN_DELETE_ALL_EMPLOYEES_RESET";

export const EMPLOYEE_GET_ALL_PAYSLIPS_REQUEST =
  "EMPLOYEE_GET_ALL_PAYSLIPS_REQUEST";
export const EMPLOYEE_GET_ALL_PAYSLIPS_SUCCESS =
  "EMPLOYEE_GET_ALL_PAYSLIPS_SUCCESS";
export const EMPLOYEE_GET_ALL_PAYSLIPS_FAIL = "EMPLOYEE_GET_ALL_PAYSLIPS_FAIL";
export const EMPLOYEE_GET_ALL_PAYSLIPS_RESET =
  "EMPLOYEE_GET_ALL_PAYSLIPS_RESET";

export const EMPLOYEE_GET_PERSONAL_DETAILS_REQUEST =
  "EMPLOYEE_GET_PERSONAL_DETAILS_REQUEST";
export const EMPLOYEE_GET_PERSONAL_DETAILS_SUCCESS =
  "EMPLOYEE_GET_PERSONAL_DETAILS_SUCCESS";
export const EMPLOYEE_GET_PERSONAL_DETAILS_FAIL =
  "EMPLOYEE_GET_PERSONAL_DETAILS_FAIL";
