export const HR_GET_ALL_GENERATED_LOANS_REQUEST =
  "HR_GET_ALL_GENERATED_LOANS_REQUEST";
export const HR_GET_ALL_GENERATED_LOANS_SUCCESS =
  "HR_GET_ALL_GENERATED_LOANS_SUCCESS";
export const HR_GET_ALL_GENERATED_LOANS_FAIL =
  "HR_GET_ALL_GENERATED_LOANS_FAIL";

export const EMPLOYEE_ASK_FOR_LOAN_REQUEST = "EMPLOYEE_ASK_FOR_LOAN_REQUEST";
export const EMPLOYEE_ASK_FOR_LOAN_SUCCESS = "EMPLOYEE_ASK_FOR_LOAN_SUCCESS";
export const EMPLOYEE_ASK_FOR_LOAN_FAIL = "EMPLOYEE_ASK_FOR_LOAN_FAIL";
export const EMPLOYEE_ASK_FOR_LOAN_RESET = "EMPLOYEE_ASK_FOR_LOAN_RESET";

export const EMPLOYEE_GET_GENERATED_LOANS_REQUEST =
  "EMPLOYEE_GET_GENERATED_LOANS_REQUEST";
export const EMPLOYEE_GET_GENERATED_LOANS_SUCCESS =
  "EMPLOYEE_GET_GENERATED_LOANS_SUCCESS";
export const EMPLOYEE_GET_GENERATED_LOANS_FAIL =
  "EMPLOYEE_GET_GENERATED_LOANS_FAIL";

export const HR_APPROVES_GENERATED_LOANS_REQUEST =
  "HR_APPROVES_GENERATED_LOANS_REQUEST";
export const HR_APPROVES_GENERATED_LOANS_SUCCESS =
  "HR_APPROVES_GENERATED_LOANS_SUCCESS";
export const HR_APPROVES_GENERATED_LOANS_FAIL =
  "HR_APPROVES_GENERATED_LOANS_FAIL";
export const HR_APPROVES_GENERATED_LOANS_RESET =
  "HR_APPROVES_GENERATED_LOANS_RESET";

export const AUDITOR_SET_PRE_APPROVED_GENERATED_LOANS_REQUEST =
  "AUDITOR_SET_PRE_APPROVED_GENERATED_LOANS_REQUEST";
export const AUDITOR_SET_PRE_APPROVED_GENERATED_LOANS_SUCCESS =
  "AUDITOR_SET_PRE_APPROVED_GENERATED_LOANS_SUCCESS";
export const AUDITOR_SET_PRE_APPROVED_GENERATED_LOANS_FAIL =
  "AUDITOR_SET_PRE_APPROVED_GENERATED_LOANS_FAIL";
export const AUDITOR_SET_PRE_APPROVED_GENERATED_LOANS_RESET =
  "AUDITOR_SET_PRE_APPROVED_GENERATED_LOANS_RESET";

export const AUDITOR_GET_NOT_APPROVED_GENERATED_LOANS_REQUEST =
  "AUDITOR_GET_NOT_APPROVED_GENERATED_LOANS_REQUEST";
export const AUDITOR_GET_NOT_APPROVED_GENERATED_LOANS_SUCCESS =
  "AUDITOR_GET_NOT_APPROVED_GENERATED_LOANS_SUCCESS";
export const AUDITOR_GET_NOT_APPROVED_GENERATED_LOANS_FAIL =
  "AUDITOR_GET_NOT_APPROVED_GENERATED_LOANS_FAIL";

export const CEO_SET_APPROVED_GENERATED_LOANS_REQUEST =
  "CEO_SET_APPROVED_GENERATED_LOANS_REQUEST";
export const CEO_SET_APPROVED_GENERATED_LOANS_SUCCESS =
  "CEO_SET_APPROVED_GENERATED_LOANS_SUCCESS";
export const CEO_SET_APPROVED_GENERATED_LOANS_FAIL =
  "CEO_SET_APPROVED_GENERATED_LOANS_FAIL";
export const CEO_SET_APPROVED_GENERATED_LOANS_RESET =
  "CEO_SET_APPROVED_GENERATED_LOANS_RESET";

export const CEO_GET_PRE_APPROVED_GENERATED_LOANS_REQUEST =
  "CEO_GET_PRE_APPROVED_GENERATED_LOANS_REQUEST";
export const CEO_GET_PRE_APPROVED_GENERATED_LOANS_SUCCESS =
  "CEO_GET_PRE_APPROVED_GENERATED_LOANS_SUCCESS";
export const CEO_GET_PRE_APPROVED_GENERATED_LOANS_FAIL =
  "CEO_GET_PRE_APPROVED_GENERATED_LOANS_FAIL";

export const CEO_GET_APPROVED_GENERATED_LOANS_REQUEST =
  "CEO_GET_APPROVED_GENERATED_LOANS_REQUEST";
export const CEO_GET_APPROVED_GENERATED_LOANS_SUCCESS =
  "CEO_GET_APPROVED_GENERATED_LOANS_SUCCESS";
export const CEO_GET_APPROVED_GENERATED_LOANS_FAIL =
  "CEO_GET_APPROVED_GENERATED_LOANS_FAIL";

export const HR_GET_REJECTED_GENERATED_LOANS_REQUEST =
  " HR_GET_REJECTED_GENERATED_LOANS_REQUEST";
export const HR_GET_REJECTED_GENERATED_LOANS_SUCCESS =
  " HR_GET_REJECTED_GENERATED_LOANS_SUCCESS";
export const HR_GET_REJECTED_GENERATED_LOANS_FAIL =
  " HR_GET_REJECTED_GENERATED_LOANS_FAIL";

export const AUDITOR_REJECT_NOT_APPROVED_GENERATED_LOANS_REQUEST =
  "AUDITOR_REJECT_NOT_APPROVED_GENERATED_LOANS_REQUEST";
export const AUDITOR_REJECT_NOT_APPROVED_GENERATED_LOANS_SUCCESS =
  "AUDITOR_REJECT_NOT_APPROVED_GENERATED_LOANS_SUCCESS";
export const AUDITOR_REJECT_NOT_APPROVED_GENERATED_LOANS_FAIL =
  "AUDITOR_REJECT_NOT_APPROVED_GENERATED_LOANS_FAIL";
export const AUDITOR_REJECT_NOT_APPROVED_GENERATED_LOANS_RESET =
  "AUDITOR_REJECT_NOT_APPROVED_GENERATED_LOANS_RESET";

export const CEO_REJECT_PRE_APPROVED_GENERATED_LOANS_REQUEST =
  "CEO_REJECT_PRE_APPROVED_GENERATED_LOANS_REQUEST";
export const CEO_REJECT_PRE_APPROVED_GENERATED_LOANS_SUCCESS =
  "CEO_REJECT_PRE_APPROVED_GENERATED_LOANS_SUCCESS";
export const CEO_REJECT_PRE_APPROVED_GENERATED_LOANS_FAIL =
  "CEO_REJECT_PRE_APPROVED_GENERATED_LOANS_FAIL";
export const CEO_REJECT_PRE_APPROVED_GENERATED_LOANS_RESET =
  "CEO_REJECT_PRE_APPROVED_GENERATED_LOANS_RESET";

export const HR_DELETE_EMPLOYEE_LOAN_BY_ID_REQUEST =
  "HR_DELETE_EMPLOYEE_LOAN_BY_ID_REQUEST";
export const HR_DELETE_EMPLOYEE_LOAN_BY_ID_SUCCESS =
  "HR_DELETE_EMPLOYEE_LOAN_BY_ID_SUCCESS";
export const HR_DELETE_EMPLOYEE_LOAN_BY_ID_FAIL =
  "HR_DELETE_EMPLOYEE_LOAN_BY_ID_FAIL";
export const HR_DELETE_EMPLOYEE_LOAN_BY_ID_RESET =
  "HR_DELETE_EMPLOYEE_LOAN_BY_ID_RESET";

export const HR_BULK_DELETE_EMPLOYEE_LOANS_REQUEST =
  "HR_BULK_DELETE_EMPLOYEE_LOANS_REQUEST";
export const HR_BULK_DELETE_EMPLOYEE_LOANS_SUCCESS =
  "HR_BULK_DELETE_EMPLOYEE_LOANS_SUCCESS";
export const HR_BULK_DELETE_EMPLOYEE_LOANS_FAIL =
  "HR_BULK_DELETE_EMPLOYEE_LOANS_FAIL";
export const HR_BULK_DELETE_EMPLOYEE_LOANS_RESET =
  "HR_BULK_DELETE_EMPLOYEE_LOANS_RESET";
