export const HR_GET_ALL_LOAN_REQUEST = "HR_GET_ALL_LOAN_REQUEST";
export const HR_GET_ALL_LOAN_SUCCESS = "HR_GET_ALL_LOAN_SUCCESS";
export const HR_GET_ALL_LOAN_FAIL = "HR_GET_ALL_LOAN_FAIL";

export const HR_CREATE_LOAN_REQUEST = "HR_CREATE_LOAN_REQUEST";
export const HR_CREATE_LOAN_SUCCESS = "HR_CREATE_LOAN_SUCCESS";
export const HR_CREATE_LOAN_FAIL = "HR_CREATE_LOAN_FAIL";
export const HR_CREATE_LOAN_RESET = "HR_CREATE_LOAN_RESET";

export const HR_UPDATE_LOAN_REQUEST = "HR_UPDATE_LOAN_REQUEST";
export const HR_UPDATE_LOAN_SUCCESS = "HR_UPDATE_LOAN_SUCCESS";
export const HR_UPDATE_LOAN_FAIL = "HR_UPDATE_LOAN_FAIL";
export const HR_UPDATE_LOAN_RESET = "HR_UPDATE_LOAN_RESET";

export const HR_DELETE_LOAN_REQUEST = "HR_DELETE_LOAN_REQUEST";
export const HR_DELETE_LOAN_SUCCESS = "HR_DELETE_LOAN_SUCCESS";
export const HR_DELETE_LOAN_FAIL = "HR_DELETE_LOAN_FAIL";
export const HR_DELETE_LOAN_RESET = "HR_DELETE_LOAN_RESET";

export const HR_UPDATE_ALL_LOANS_REPAYMENT_PERCENTAGE_REQUEST =
  "HR_UPDATE_ALL_LOANS_REPAYMENT_PERCENTAGE_REQUEST";
export const HR_UPDATE_ALL_LOANS_REPAYMENT_PERCENTAGE_SUCCESS =
  "HR_UPDATE_ALL_LOANS_REPAYMENT_PERCENTAGE_SUCCESS";
export const HR_UPDATE_ALL_LOANS_REPAYMENT_PERCENTAGE_FAIL =
  "HR_UPDATE_ALL_LOANS_REPAYMENT_PERCENTAGE_FAIL";
export const HR_UPDATE_ALL_LOANS_REPAYMENT_PERCENTAGE_RESET =
  "HR_UPDATE_ALL_LOANS_REPAYMENT_PERCENTAGE_RESET";

export const HR_UPDATE_MANAGEMENT_CAR_LOAN_REQUEST =
  "HR_UPDATE_MANAGEMENT_CAR_LOAN_REQUEST";
export const HR_UPDATE_MANAGEMENT_CAR_LOAN_SUCCESS =
  "HR_UPDATE_MANAGEMENT_CAR_LOAN_SUCCESS";
export const HR_UPDATE_MANAGEMENT_CAR_LOAN_FAIL =
  "HR_UPDATE_MANAGEMENT_CAR_LOAN_FAIL";
export const HR_UPDATE_MANAGEMENT_CAR_LOAN_RESET =
  "HR_UPDATE_MANAGEMENT_CAR_LOAN_RESET";
