export const ADMIN_GET_MONTHLYPAYHEADS_REQUEST =
  "ADMIN_GET_MONTHLYPAYHEADS_REQUEST";
export const ADMIN_GET_MONTHLYPAYHEADS_SUCCESS =
  "ADMIN_GET_MONTHLYPAYHEADS_SUCCESS";
export const ADMIN_GET_MONTHLYPAYHEADS_FAIL = "ADMIN_GET_MONTHLYPAYHEADS_FAIL";
export const ADMIN_GET_MONTHLYPAYHEADS_RESET =
  "ADMIN_GET_MONTHLYPAYHEADS_RESET";

export const ADMIN_CREATE_MONTHLYPAYHEADS_REQUEST =
  "ADMIN_CREATE_MONTHLYPAYHEADS_REQUEST";
export const ADMIN_CREATE_MONTHLYPAYHEADS_SUCCESS =
  "ADMIN_CREATE_MONTHLYPAYHEADS_SUCCESS";
export const ADMIN_CREATE_MONTHLYPAYHEADS_FAIL =
  "ADMIN_CREATE_MONTHLYPAYHEADS_FAIL";
export const ADMIN_CREATE_MONTHLYPAYHEADS_RESET =
  "ADMIN_CREATE_MONTHLYPAYHEADS_RESET";

export const ADMIN_UPDATE_MONTHLYPAYHEADS_REQUEST =
  "ADMIN_UPDATE_MONTHLYPAYHEADS_REQUEST";
export const ADMIN_UPDATE_MONTHLYPAYHEADS_SUCCESS =
  "ADMIN_UPDATE_MONTHLYPAYHEADS_SUCCESS";
export const ADMIN_UPDATE_MONTHLYPAYHEADS_FAIL =
  "ADMIN_UPDATE_MONTHLYPAYHEADS_FAIL";
export const ADMIN_UPDATE_MONTHLYPAYHEADS_RESET =
  "ADMIN_UPDATE_MONTHLYPAYHEADS_RESET";

export const ADMIN_DELETE_MONTHLYPAYHEADS_REQUEST =
  "ADMIN_DELETE_MONTHLYPAYHEADS_REQUEST";
export const ADMIN_DELETE_MONTHLYPAYHEADS_SUCCESS =
  "ADMIN_DELETE_MONTHLYPAYHEADS_SUCCESS";
export const ADMIN_DELETE_MONTHLYPAYHEADS_FAIL =
  "ADMIN_DELETE_MONTHLYPAYHEADS_FAIL";
export const ADMIN_DELETE_MONTHLYPAYHEADS_RESET =
  "ADMIN_DELETE_MONTHLYPAYHEADS_RESET";
