export const GENERATE_PAYSLIP_REQUEST = "GENERATE_PAYSLIP_REQUEST";
export const GENERATE_PAYSLIP_SUCCESS = "GENERATE_PAYSLIP_SUCCESS";
export const GENERATE_PAYSLIP_FAIL = "GENERATE_PAYSLIP_FAIL";
export const GENERATE_PAYSLIP_RESET = "GENERATE_PAYSLIP_RESET";

export const ADMIN_GENERATE_BULK_PAYSLIPS_REQUEST =
  "ADMIN_GENERATE_BULK_PAYSLIPS_REQUEST";
export const ADMIN_GENERATE_BULK_PAYSLIPS_SUCCESS =
  "ADMIN_GENERATE_BULK_PAYSLIPS_SUCCESS";
export const ADMIN_GENERATE_BULK_PAYSLIPS_FAIL =
  "ADMIN_GENERATE_BULK_PAYSLIPS_FAIL";
export const ADMIN_GENERATE_BULK_PAYSLIPS_RESET =
  "ADMIN_GENERATE_BULK_PAYSLIPS_RESET";

export const ADMIN_GENERATE_BULK_PAYSLIPS_ALL_REQUEST =
  "ADMIN_GENERATE_BULK_PAYSLIPS_ALL_REQUEST";
export const ADMIN_GENERATE_BULK_PAYSLIPS_ALL_SUCCESS =
  "ADMIN_GENERATE_BULK_PAYSLIPS_ALL_SUCCESS";
export const ADMIN_GENERATE_BULK_PAYSLIPS_ALL_FAIL =
  "ADMIN_GENERATE_BULK_PAYSLIPS_ALL_FAIL";
export const ADMIN_GENERATE_BULK_PAYSLIPS_ALL_RESET =
  "ADMIN_GENERATE_BULK_PAYSLIPS_ALL_RESET";

export const ADMIN_DELETE_BULK_PAYSLIPS_REQUEST =
  "ADMIN_DELETE_BULK_PAYSLIPS_REQUEST";
export const ADMIN_DELETE_BULK_PAYSLIPS_SUCCESS =
  "ADMIN_DELETE_BULK_PAYSLIPS_SUCCESS";
export const ADMIN_DELETE_BULK_PAYSLIPS_FAIL =
  "ADMIN_DELETE_BULK_PAYSLIPS_FAIL";
export const ADMIN_DELETE_BULK_PAYSLIPS_RESET =
  "ADMIN_DELETE_BULK_PAYSLIPS_RESET";

export const GET_ALL_GENERATED_PAYSLIP_REQUEST =
  "GET_ALL_GENERATED_PAYSLIP_REQUEST";
export const GET_ALL_GENERATED_PAYSLIP_SUCCESS =
  "GET_ALL_GENERATED_PAYSLIP_SUCCESS";
export const GET_ALL_GENERATED_PAYSLIP_FAIL = "GET_ALL_GENERATED_PAYSLIP_FAIL";
export const GET_ALL_GENERATED_PAYSLIP_RESET =
  "GET_ALL_GENERATED_PAYSLIP_RESET";

export const HR_GET_REJECTED_PAYSLIPS_REQUEST =
  "HR_GET_REJECTED_PAYSLIPS_REQUEST";
export const HR_GET_REJECTED_PAYSLIPS_SUCCESS =
  "HR_GET_REJECTED_PAYSLIPS_SUCCESS";
export const HR_GET_REJECTED_PAYSLIPS_FAIL = "HR_GET_REJECTED_PAYSLIPS_FAIL";
export const HR_GET_REJECTED_PAYSLIPS_RESET = "HR_GET_REJECTED_PAYSLIPS_RESET";

export const HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_REQUEST =
  "HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_REQUEST";
export const HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_SUCCESS =
  "HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_SUCCESS";
export const HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_FAIL =
  "HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_FAIL";
export const HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_RESET =
  "HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_RESET";

export const HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_ALL_REQUEST =
  "HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_ALL_REQUEST";
export const HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_ALL_SUCCESS =
  "HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_ALL_SUCCESS";
export const HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_ALL_FAIL =
  "HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_ALL_FAIL";
export const HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_ALL_RESET =
  "HR_SET_NOT_APPROVED_GENERATED_PAYSLIPS_ALL_RESET";

export const AUDITOR_GET_NOT_APPROVED_SALARYSLIPS_REQUEST =
  "AUDITOR_GET_NOT_APPROVED_SALARYSLIPS_REQUEST";
export const AUDITOR_GET_NOT_APPROVED_SALARYSLIPS_SUCCESS =
  "AUDITOR_GET_NOT_APPROVED_SALARYSLIPS_SUCCESS";
export const AUDITOR_GET_NOT_APPROVED_SALARYSLIPS_FAIL =
  "AUDITOR_GET_NOT_APPROVED_SALARYSLIPS_FAIL";
export const AUDITOR_GET_NOT_APPROVED_SALARYSLIPS_RESET =
  "AUDITOR_GET_NOT_APPROVED_SALARYSLIPS_RESET";

export const AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_REQUEST =
  "AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_REQUEST";
export const AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_SUCCESS =
  "AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_SUCCESS";
export const AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_FAIL =
  "AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_FAIL";
export const AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_RESET =
  "AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_RESET";

export const AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_ALL_REQUEST =
  "AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_ALL_REQUEST";
export const AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_ALL_SUCCESS =
  "AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_ALL_SUCCESS";
export const AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_ALL_FAIL =
  "AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_ALL_FAIL";
export const AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_ALL_RESET =
  "AUDITOR_SET_PRE_APPROVED_GENERATED_PAYSLIPS_ALL_RESET";

export const AUDITOR_REJECT_NOT_APPROVED_PAYSLIPS_REQUEST =
  "AUDITOR_REJECT_NOT_APPROVED_PAYSLIPS_REQUEST";
export const AUDITOR_REJECT_NOT_APPROVED_PAYSLIPS_SUCCESS =
  "AUDITOR_REJECT_NOT_APPROVED_PAYSLIPS_SUCCESS";
export const AUDITOR_REJECT_NOT_APPROVED_PAYSLIPS_FAIL =
  "AUDITOR_REJECT_NOT_APPROVED_PAYSLIPS_FAIL";
export const AUDITOR_REJECT_NOT_APPROVED_PAYSLIPS_RESET =
  "AUDITOR_REJECT_NOT_APPROVED_PAYSLIPS_RESET";

export const CEO_REJECT_PRE_APPROVED_PAYSLIPS_REQUEST =
  "CEO_REJECT_PRE_APPROVED_PAYSLIPS_REQUEST";
export const CEO_REJECT_PRE_APPROVED_PAYSLIPS_SUCCESS =
  "CEO_REJECT_PRE_APPROVED_PAYSLIPS_SUCCESS";
export const CEO_REJECT_PRE_APPROVED_PAYSLIPS_FAIL =
  "CEO_REJECT_PRE_APPROVED_PAYSLIPS_FAIL";
export const CEO_REJECT_PRE_APPROVED_PAYSLIPS_RESET =
  "CEO_REJECT_PRE_APPROVED_PAYSLIPS_RESET";

export const CEO_GET_APPROVED_SALARYSLIPS_REQUEST =
  "CEO_GET_APPROVED_SALARYSLIPS_REQUEST";
export const CEO_GET_APPROVED_SALARYSLIPS_SUCCESS =
  "CEO_GET_APPROVED_SALARYSLIPS_SUCCESS";
export const CEO_GET_APPROVED_SALARYSLIPS_FAIL =
  "CEO_GET_APPROVED_SALARYSLIPS_FAIL";

export const CEO_GET_PRE_APPROVED_SALARYSLIPS_REQUEST =
  "CEO_GET_PRE_APPROVED_SALARYSLIPS_REQUEST";
export const CEO_GET_PRE_APPROVED_SALARYSLIPS_SUCCESS =
  "CEO_GET_PRE_APPROVED_SALARYSLIPS_SUCCESS";
export const CEO_GET_PRE_APPROVED_SALARYSLIPS_FAIL =
  "CEO_GET_PRE_APPROVED_SALARYSLIPS_FAIL";

export const ACCOUNTANT_GET_APPROVED_SALARYSLIPS_REQUEST =
  "ACCOUNTANT_GET_APPROVED_SALARYSLIPS_REQUEST";
export const ACCOUNTANT_GET_APPROVED_SALARYSLIPS_SUCCESS =
  "ACCOUNTANT_GET_APPROVED_SALARYSLIPS_SUCCESS";
export const ACCOUNTANT_GET_APPROVED_SALARYSLIPS_FAIL =
  "ACCOUNTANT_GET_APPROVED_SALARYSLIPS_FAIL";
export const ACCOUNTANT_GET_APPROVED_SALARYSLIPS_RESET =
  "ACCOUNTANT_GET_APPROVED_SALARYSLIPS_RESET";

export const CEO_SET_APPROVED_GENERATED_PAYSLIPS_REQUEST =
  "CEO_SET_APPROVED_GENERATED_PAYSLIPS_REQUEST";
export const CEO_SET_APPROVED_GENERATED_PAYSLIPS_SUCCESS =
  "CEO_SET_APPROVED_GENERATED_PAYSLIPS_SUCCESS";
export const CEO_SET_APPROVED_GENERATED_PAYSLIPS_FAIL =
  "CEO_SET_APPROVED_GENERATED_PAYSLIPS_FAIL";
export const CEO_SET_APPROVED_GENERATED_PAYSLIPS_RESET =
  "CEO_SET_APPROVED_GENERATED_PAYSLIPS_RESET";

export const CEO_SET_APPROVED_GENERATED_PAYSLIPS_ALL_REQUEST =
  "CEO_SET_APPROVED_GENERATED_PAYSLIPS_ALL_REQUEST";
export const CEO_SET_APPROVED_GENERATED_PAYSLIPS_ALL_SUCCESS =
  "CEO_SET_APPROVED_GENERATED_PAYSLIPS_ALL_SUCCESS";
export const CEO_SET_APPROVED_GENERATED_PAYSLIPS_ALL_FAIL =
  "CEO_SET_APPROVED_GENERATED_PAYSLIPS_ALL_FAIL";
export const CEO_SET_APPROVED_GENERATED_PAYSLIPS_ALL_RESET =
  "CEO_SET_APPROVED_GENERATED_PAYSLIPS_ALL_RESET";

export const DELETE_GENERATED_PAYSLIP_BY_ID_REQUEST =
  "DELETE_GENERATED_PAYSLIP_BY_ID_REQUEST";
export const DELETE_GENERATED_PAYSLIP_BY_ID_SUCCESS =
  "DELETE_GENERATED_PAYSLIP_BY_ID_SUCCESS";
export const DELETE_GENERATED_PAYSLIP_BY_ID_FAIL =
  "DELETE_GENERATED_PAYSLIP_BY_ID_FAIL";
export const DELETE_GENERATED_PAYSLIP_BY_ID_RESET =
  "DELETE_GENERATED_PAYSLIP_BY_ID_RESET";

export const AUDITOR_AND_CEO_REJECT_EXCEL_PAYSLIPS_REQUEST =
  "AUDITOR_AND_CEO_REJECT_EXCEL_PAYSLIPS_REQUEST";
export const AUDITOR_AND_CEO_REJECT_EXCEL_PAYSLIPS_SUCCESS =
  "AUDITOR_AND_CEO_REJECT_EXCEL_PAYSLIPS_SUCCESS";
export const AUDITOR_AND_CEO_REJECT_EXCEL_PAYSLIPS_FAIL =
  "AUDITOR_AND_CEO_REJECT_EXCEL_PAYSLIPS_FAIL";
export const AUDITOR_AND_CEO_REJECT_EXCEL_PAYSLIPS_RESET =
  "AUDITOR_AND_CEO_REJECT_EXCEL_PAYSLIPS_RESET";
