export const ADMIN_GET_ALL_POSITION_REQUEST = "ADMIN_GET_ALL_POSITION_REQUEST";
export const ADMIN_GET_ALL_POSITION_SUCCESS = "ADMIN_GET_ALL_POSITION_SUCCESS";
export const ADMIN_GET_ALL_POSITION_FAIL = "ADMIN_GET_ALL_POSITION_FAIL";
export const ADMIN_GET_ALL_POSITION_RESET = "ADMIN_GET_ALL_POSITION_RESET";

export const ADMIN_CREATE_POSITION_REQUEST = "ADMIN_CREATE_POSITION_REQUEST";
export const ADMIN_CREATE_POSITION_SUCCESS = "ADMIN_CREATE_POSITION_SUCCESS";
export const ADMIN_CREATE_POSITION_FAIL = "ADMIN_CREATE_POSITION_FAIL";
export const ADMIN_CREATE_POSITION_RESET = "ADMIN_CREATE_POSITION_RESET";

export const ADMIN_UPDATE_POSITION_BY_ID_REQUEST =
  "ADMIN_UPDATE_POSITION_BY_ID_REQUEST";
export const ADMIN_UPDATE_POSITION_BY_ID_SUCCESS =
  "ADMIN_UPDATE_POSITION_BY_ID_SUCCESS";
export const ADMIN_UPDATE_POSITION_BY_ID_FAIL =
  "ADMIN_UPDATE_POSITION_BY_ID_FAIL";
export const ADMIN_UPDATE_POSITION_BY_ID_RESET =
  "ADMIN_UPDATE_POSITION_BY_ID_RESET";

export const ADMIN_DELETE_POSITION_BY_ID_REQUEST =
  "ADMIN_DELETE_POSITION_BY_ID_REQUEST";
export const ADMIN_DELETE_POSITION_BY_ID_SUCCESS =
  "ADMIN_DELETE_POSITION_BY_ID_SUCCESS";
export const ADMIN_DELETE_POSITION_BY_ID_FAIL =
  "ADMIN_DELETE_POSITION_BY_ID_FAIL";
export const ADMIN_DELETE_POSITION_BY_ID_RESET =
  "ADMIN_DELETE_POSITION_BY_ID_RESET";
