export const HR_CREATE_JUNIOR_STAFF_GRADE_REQUEST =
  "HR_CREATE_JUNIOR_STAFF_GRADE_REQUEST";
export const HR_CREATE_JUNIOR_STAFF_GRADE_SUCCESS =
  "HR_CREATE_JUNIOR_STAFF_GRADE_SUCCESS";
export const HR_CREATE_JUNIOR_STAFF_GRADE_FAIL =
  "HR_CREATE_JUNIOR_STAFF_GRADE_FAIL";
export const HR_CREATE_JUNIOR_STAFF_GRADE_RESET =
  "HR_CREATE_JUNIOR_STAFF_GRADE_RESET";

export const HR_CREATE_MIDDLE_STAFF_GRADE_REQUEST =
  "HR_CREATE_MIDDLE_STAFF_GRADE_REQUEST";
export const HR_CREATE_MIDDLE_STAFF_GRADE_SUCCESS =
  "HR_CREATE_MIDDLE_STAFF_GRADE_SUCCESS";
export const HR_CREATE_MIDDLE_STAFF_GRADE_FAIL =
  "HR_CREATE_MIDDLE_STAFF_GRADE_FAIL";
export const HR_CREATE_MIDDLE_STAFF_GRADE_RESET =
  "HR_CREATE_MIDDLE_STAFF_GRADE_RESET";

export const HR_CREATE_SENIOR_STAFF_GRADE_REQUEST =
  "HR_CREATE_SENIOR_STAFF_GRADE_REQUEST";
export const HR_CREATE_SENIOR_STAFF_GRADE_SUCCESS =
  "HR_CREATE_SENIOR_STAFF_GRADE_SUCCESS";
export const HR_CREATE_SENIOR_STAFF_GRADE_FAIL =
  "HR_CREATE_SENIOR_STAFF_GRADE_FAIL";
export const HR_CREATE_SENIOR_STAFF_GRADE_RESET =
  "HR_CREATE_SENIOR_STAFF_GRADE_RESET";

export const HR_CREATE_MANAGEMENT_STAFF_GRADE_REQUEST =
  "HR_CREATE_MANAGEMENT_STAFF_GRADE_REQUEST";
export const HR_CREATE_MANAGEMENT_STAFF_GRADE_SUCCESS =
  "HR_CREATE_MANAGEMENT_STAFF_GRADE_SUCCESS";
export const HR_CREATE_MANAGEMENT_STAFF_GRADE_FAIL =
  "HR_CREATE_MANAGEMENT_STAFF_GRADE_FAIL";
export const HR_CREATE_MANAGEMENT_STAFF_GRADE_RESET =
  "HR_CREATE_MANAGEMENT_STAFF_GRADE_RESET";
