export const HR_GET_STEPS_REQUEST = "HR_GET_STEPS_REQUEST";
export const HR_GET_STEPS_SUCCESS = "HR_GET_STEPS_SUCCESS";
export const HR_GET_STEPS_FAIL = "HR_GET_STEPS_FAIL";
export const HR_GET_STEPS_RESET = "HR_GET_STEPS_RESET";

export const HR_GET_STEPS_BY_SALARYLEVEL_REQUEST =
  "HR_GET_STEPS_BY_SALARYLEVEL_REQUEST";
export const HR_GET_STEPS_BY_SALARYLEVEL_SUCCESS =
  "HR_GET_STEPS_BY_SALARYLEVEL_SUCCESS";
export const HR_GET_STEPS_BY_SALARYLEVEL_FAIL =
  "HR_GET_STEPS_BY_SALARYLEVEL_FAIL";
export const HR_GET_STEPS_BY_SALARYLEVEL_RESET =
  "HR_GET_STEPS_BY_SALARYLEVEL_RESET";

export const HR_CREATE_STEPS_REQUEST = "HR_CREATE_STEPS_REQUEST";
export const HR_CREATE_STEPS_SUCCESS = "HR_CREATE_STEPS_SUCCESS";
export const HR_CREATE_STEPS_FAIL = "HR_CREATE_STEPS_FAIL";
export const HR_CREATE_STEPS_RESET = "HR_CREATE_STEPS_RESET";

export const HR_UPDATE_STEPS_BY_ID_REQUEST = "HR_UPDATE_STEPS_BY_ID_REQUEST";
export const HR_UPDATE_STEPS_BY_ID_SUCCESS = "HR_UPDATE_STEPS_BY_ID_SUCCESS";
export const HR_UPDATE_STEPS_BY_ID_FAIL = "HR_UPDATE_STEPS_BY_ID_FAIL";
export const HR_UPDATE_STEPS_BY_ID_RESET = "HR_UPDATE_STEPS_BY_ID_RESET";

export const HR_DELETE_STEPS_BY_ID_REQUEST = "HR_DELETE_STEPS_BY_ID_REQUEST";
export const HR_DELETE_STEPS_BY_ID_SUCCESS = "HR_DELETE_STEPS_BY_ID_SUCCESS";
export const HR_DELETE_STEPS_BY_ID_FAIL = "HR_DELETE_STEPS_BY_ID_FAIL";
export const HR_DELETE_STEPS_BY_ID_RESET = "HR_DELETE_STEPS_BY_ID_RESET";
