export const HR_GET_SALARYLEVEL_REQUEST = "HR_GET_SALARYLEVEL_REQUEST";
export const HR_GET_SALARYLEVEL_SUCCESS = "HR_GET_SALARYLEVEL_SUCCESS";
export const HR_GET_SALARYLEVEL_FAIL = "HR_GET_SALARYLEVEL_FAIL";
export const HR_GET_SALARYLEVEL_RESET = "HR_GET_SALARYLEVEL_RESET";

export const HR_GET_SALARYLEVEL_BY_SALARYGRADE_REQUEST =
  "HR_GET_SALARYLEVEL_BY_SALARYGRADE_REQUEST";
export const HR_GET_SALARYLEVEL_BY_SALARYGRADE_SUCCESS =
  "HR_GET_SALARYLEVEL_BY_SALARYGRADE_SUCCESS";
export const HR_GET_SALARYLEVEL_BY_SALARYGRADE_FAIL =
  "HR_GET_SALARYLEVEL_BY_SALARYGRADE_FAIL";
export const HR_GET_SALARYLEVEL_BY_SALARYGRADE_RESET =
  "HR_GET_SALARYLEVEL_BY_SALARYGRADE_RESET";

export const HR_CREATE_SALARYLEVEL_REQUEST = "HR_CREATE_SALARYLEVEL_REQUEST";
export const HR_CREATE_SALARYLEVEL_SUCCESS = "HR_CREATE_SALARYLEVEL_SUCCESS";
export const HR_CREATE_SALARYLEVEL_FAIL = "HR_CREATE_SALARYLEVEL_FAIL";
export const HR_CREATE_SALARYLEVEL_RESET = "HR_CREATE_SALARYLEVEL_RESET";

export const HR_UPDATE_SALARYLEVEL_BY_ID_REQUEST =
  "HR_UPDATE_SALARYLEVEL_BY_ID_REQUEST";
export const HR_UPDATE_SALARYLEVEL_BY_ID_SUCCESS =
  "HR_UPDATE_SALARYLEVEL_BY_ID_SUCCESS";
export const HR_UPDATE_SALARYLEVEL_BY_ID_FAIL =
  "HR_UPDATE_SALARYLEVEL_BY_ID_FAIL";
export const HR_UPDATE_SALARYLEVEL_BY_ID_RESET =
  "HR_UPDATE_SALARYLEVEL_BY_ID_RESET";

export const HR_DELETE_SALARYLEVEL_BY_ID_REQUEST =
  "HR_DELETE_SALARYLEVEL_BY_ID_REQUEST";
export const HR_DELETE_SALARYLEVEL_BY_ID_SUCCESS =
  "HR_DELETE_SALARYLEVEL_BY_ID_SUCCESS";
export const HR_DELETE_SALARYLEVEL_BY_ID_FAIL =
  "HR_DELETE_SALARYLEVEL_BY_ID_FAIL";
export const HR_DELETE_SALARYLEVEL_BY_ID_RESET =
  "HR_DELETE_SALARYLEVEL_BY_ID_RESET";
