export const HR_GET_STAFFGRADE_REQUEST = "HR_GET_STAFFGRADE_REQUEST";
export const HR_GET_STAFFGRADE_SUCCESS = "HR_GET_STAFFGRADE_SUCCESS";
export const HR_GET_STAFFGRADE_FAIL = "HR_GET_STAFFGRADE_FAIL";
export const HR_GET_STAFFGRADE_RESET = "HR_GET_STAFFGRADE_RESET";

export const HR_CREATE_STAFFGRADE_REQUEST = "HR_CREATE_STAFFGRADE_REQUEST";
export const HR_CREATE_STAFFGRADE_SUCCESS = "HR_CREATE_STAFFGRADE_SUCCESS";
export const HR_CREATE_STAFFGRADE_FAIL = "HR_CREATE_STAFFGRADE_FAIL";
export const HR_CREATE_STAFFGRADE_RESET = "HR_CREATE_STAFFGRADE_RESET";

export const HR_UPDATE_STAFFGRADE_BY_ID_REQUEST =
  "HR_UPDATE_STAFFGRADE_BY_ID_REQUEST";
export const HR_UPDATE_STAFFGRADE_BY_ID_SUCCESS =
  "HR_UPDATE_STAFFGRADE_BY_ID_SUCCESS";
export const HR_UPDATE_STAFFGRADE_BY_ID_FAIL =
  "HR_UPDATE_STAFFGRADE_BY_ID_FAIL";
export const HR_UPDATE_STAFFGRADE_BY_ID_RESET =
  "HR_UPDATE_STAFFGRADE_BY_ID_RESET";

export const HR_DELETE_STAFFGRADE_BY_ID_REQUEST =
  "HR_DELETE_STAFFGRADE_BY_ID_REQUEST";
export const HR_DELETE_STAFFGRADE_BY_ID_SUCCESS =
  "HR_DELETE_STAFFGRADE_BY_ID_SUCCESS";
export const HR_DELETE_STAFFGRADE_BY_ID_FAIL =
  "HR_DELETE_STAFFGRADE_BY_ID_FAIL";
export const HR_DELETE_STAFFGRADE_BY_ID_RESET =
  "HR_DELETE_STAFFGRADE_BY_ID_RESET";
