export const ADMIN_GET_ALL_STAFFLEVEL_REQUEST =
  "ADMIN_GET_ALL_STAFFLEVEL_REQUEST";
export const ADMIN_GET_ALL_STAFFLEVEL_SUCCESS =
  "ADMIN_GET_ALL_STAFFLEVEL_SUCCESS";
export const ADMIN_GET_ALL_STAFFLEVEL_FAIL = "ADMIN_GET_ALL_STAFFLEVEL_FAIL";
export const ADMIN_GET_ALL_STAFFLEVEL_RESET = "ADMIN_GET_ALL_STAFFLEVEL_RESET";

export const ADMIN_CREATE_STAFFLEVEL_REQUEST =
  "ADMIN_CREATE_STAFFLEVEL_REQUEST";
export const ADMIN_CREATE_STAFFLEVEL_SUCCESS =
  "ADMIN_CREATE_STAFFLEVEL_SUCCESS";
export const ADMIN_CREATE_STAFFLEVEL_FAIL = "ADMIN_CREATE_STAFFLEVEL_FAIL";
export const ADMIN_CREATE_STAFFLEVEL_RESET = "ADMIN_CREATE_STAFFLEVEL_RESET";

export const ADMIN_UPDATE_STAFFLEVEL_REQUEST =
  "ADMIN_UPDATE_STAFFLEVEL_REQUEST";
export const ADMIN_UPDATE_STAFFLEVEL_SUCCESS =
  "ADMIN_UPDATE_STAFFLEVEL_SUCCESS";
export const ADMIN_UPDATE_STAFFLEVEL_FAIL = "ADMIN_UPDATE_STAFFLEVEL_FAIL";
export const ADMIN_UPDATE_STAFFLEVEL_RESET = "ADMIN_UPDATE_STAFFLEVEL_RESET";

export const ADMIN_DELETE_STAFFLEVEL_REQUEST =
  "ADMIN_DELETE_STAFFLEVEL_REQUEST";
export const ADMIN_DELETE_STAFFLEVEL_SUCCESS =
  "ADMIN_DELETE_STAFFLEVEL_SUCCESS";
export const ADMIN_DELETE_STAFFLEVEL_FAIL = "ADMIN_DELETE_STAFFLEVEL_FAIL";
export const ADMIN_DELETE_STAFFLEVEL_RESET = "ADMIN_DELETE_STAFFLEVEL_RESET";
