export const SUPER_ADMIN_GET_ALL_USERS_REQUEST = "SUPER_ADMIN_GET_ALL_USERS_REQUEST";
export const SUPER_ADMIN_GET_ALL_USERS_SUCCESS = "SUPER_ADMIN_GET_ALL_USERS_SUCCESS";
export const SUPER_ADMIN_GET_ALL_USERS_FAIL = "SUPER_ADMIN_GET_ALL_USERS_FAIL";
export const SUPER_ADMIN_GET_ALL_USERS_RESET = "SUPER_ADMIN_GET_ALL_USERS_RESET";

export const SUPER_ADMIN_UPDATE_USER_REQUEST = "SUPER_ADMIN_UPDATE_USER_REQUEST";
export const SUPER_ADMIN_UPDATE_USER_SUCCESS = "SUPER_ADMIN_UPDATE_USER_SUCCESS";
export const SUPER_ADMIN_UPDATE_USER_FAIL = "SUPER_ADMIN_UPDATE_USER_FAIL";
export const SUPER_ADMIN_UPDATE_USER_RESET = "SUPER_ADMIN_UPDATE_USER_RESET";

export const SUPER_ADMIN_UPDATE_USER_ROLE_REQUEST = "SUPER_ADMIN_UPDATE_USER_ROLE_REQUEST";
export const SUPER_ADMIN_UPDATE_USER_ROLE_SUCCESS = "SUPER_ADMIN_UPDATE_USER_ROLE_SUCCESS";
export const SUPER_ADMIN_UPDATE_USER_ROLE_FAIL = "SUPER_ADMIN_UPDATE_USER_ROLE_FAIL";
export const SUPER_ADMIN_UPDATE_USER_ROLE_RESET = "SUPER_ADMIN_UPDATE_USER_ROLE_RESET";

export const SUPER_ADMIN_DELETE_USER_REQUEST = "SUPER_ADMIN_DELETE_USER_REQUEST";
export const SUPER_ADMIN_DELETE_USER_SUCCESS = "SUPER_ADMIN_DELETE_USER_SUCCESS";
export const SUPER_ADMIN_DELETE_USER_FAIL = "SUPER_ADMIN_DELETE_USER_FAIL";
export const SUPER_ADMIN_DELETE_USER_RESET = "SUPER_ADMIN_DELETE_USER_RESET";

export const SUPER_ADMIN_BULK_DELETE_USERS_REQUEST = "SUPER_ADMIN_BULK_DELETE_USERS_REQUEST";
export const SUPER_ADMIN_BULK_DELETE_USERS_SUCCESS = "SUPER_ADMIN_BULK_DELETE_USERS_SUCCESS";
export const SUPER_ADMIN_BULK_DELETE_USERS_FAIL = "SUPER_ADMIN_BULK_DELETE_USERS_FAIL";
export const SUPER_ADMIN_BULK_DELETE_USERS_RESET = "SUPER_ADMIN_BULK_DELETE_USERS_RESET";

export const SUPER_ADMIN_GET_ALL_LOGS_REQUEST = "SUPER_ADMIN_GET_ALL_LOGS_REQUEST";
export const SUPER_ADMIN_GET_ALL_LOGS_SUCCESS = "SUPER_ADMIN_GET_ALL_LOGS_SUCCESS";
export const SUPER_ADMIN_GET_ALL_LOGS_FAIL = "SUPER_ADMIN_GET_ALL_LOGS_FAIL";
export const SUPER_ADMIN_GET_ALL_LOGS_RESET = "SUPER_ADMIN_GET_ALL_LOGS_RESET";