export const ACCOUNTANT_CREATE_NOT_APPROVED_VOUCHERS_FROM_SALARYSLIPS_REQUEST =
  "ACCOUNTANT_CREATE_NOT_APPROVED_VOUCHERS_FROM_SALARYSLIPS_REQUEST";
export const ACCOUNTANT_CREATE_NOT_APPROVED_VOUCHERS_FROM_SALARYSLIPS_SUCCESS =
  "ACCOUNTANT_CREATE_NOT_APPROVED_VOUCHERS_FROM_SALARYSLIPS_SUCCESS";
export const ACCOUNTANT_CREATE_NOT_APPROVED_VOUCHERS_FROM_SALARYSLIPS_FAIL =
  "ACCOUNTANT_CREATE_NOT_APPROVED_VOUCHERS_FROM_SALARYSLIPS_FAIL";
export const ACCOUNTANT_CREATE_NOT_APPROVED_VOUCHERS_FROM_SALARYSLIPS_RESET =
  "ACCOUNTANT_CREATE_NOT_APPROVED_VOUCHERS_FROM_SALARYSLIPS_RESET";

export const ACCOUNTANT_GET_APPROVED_VOUCHERS_REQUEST =
  "ACCOUNTANT_GET_APPROVED_VOUCHERS_REQUEST";
export const ACCOUNTANT_GET_APPROVED_VOUCHERS_SUCCESS =
  "ACCOUNTANT_GET_APPROVED_VOUCHERS_SUCCESS";
export const ACCOUNTANT_GET_APPROVED_VOUCHERS_FAIL =
  "ACCOUNTANT_GET_APPROVED_VOUCHERS_FAIL";

export const ACCOUNTANT_GET_REJECTED_VOUCHERS_REQUEST =
  "ACCOUNTANT_GET_REJECTED_VOUCHERS_REQUEST";
export const ACCOUNTANT_GET_REJECTED_VOUCHERS_SUCCESS =
  "ACCOUNTANT_GET_REJECTED_VOUCHERS_SUCCESS";
export const ACCOUNTANT_GET_REJECTED_VOUCHERS_FAIL =
  "ACCOUNTANT_GET_REJECTED_VOUCHERS_FAIL";

export const AUDITOR_GET_NOT_APPROVED_VOUCHERS_REQUEST =
  "AUDITOR_GET_NOT_APPROVED_VOUCHERS_REQUEST";
export const AUDITOR_GET_NOT_APPROVED_VOUCHERS_SUCCESS =
  "AUDITOR_GET_NOT_APPROVED_VOUCHERS_SUCCESS";
export const AUDITOR_GET_NOT_APPROVED_VOUCHERS_FAIL =
  "AUDITOR_GET_NOT_APPROVED_VOUCHERS_FAIL";

export const AUDITOR_PRE_APPROVE_VOUCHERS_REQUEST =
  "AUDITOR_PRE_APPROVE_VOUCHERS_REQUEST";
export const AUDITOR_PRE_APPROVE_VOUCHERS_SUCCESS =
  "AUDITOR_PRE_APPROVE_VOUCHERS_SUCCESS";
export const AUDITOR_PRE_APPROVE_VOUCHERS_FAIL =
  "AUDITOR_PRE_APPROVE_VOUCHERS_FAIL";
export const AUDITOR_PRE_APPROVE_VOUCHERS_RESET =
  "AUDITOR_PRE_APPROVE_VOUCHERS_RESET";

export const CEO_GET_PRE_APPROVED_VOUCHERS_REQUEST =
  "CEO_GET_PRE_APPROVED_VOUCHERS_REQUEST";
export const CEO_GET_PRE_APPROVED_VOUCHERS_SUCCESS =
  "CEO_GET_PRE_APPROVED_VOUCHERS_SUCCESS";
export const CEO_GET_PRE_APPROVED_VOUCHERS_FAIL =
  "CEO_GET_PRE_APPROVED_VOUCHERS_FAIL";

export const CEO_APPROVE_PRE_APPROVED_VOUCHERS_REQUEST =
  "CEO_APPROVE_PRE_APPROVED_VOUCHERS_REQUEST";
export const CEO_APPROVE_PRE_APPROVED_VOUCHERS_SUCCESS =
  "CEO_APPROVE_PRE_APPROVED_VOUCHERS_SUCCESS";
export const CEO_APPROVE_PRE_APPROVED_VOUCHERS_FAIL =
  "CEO_APPROVE_PRE_APPROVED_VOUCHERS_FAIL";
export const CEO_APPROVE_PRE_APPROVED_VOUCHERS_RESET =
  "CEO_APPROVE_PRE_APPROVED_VOUCHERS_RESET";

export const AUDITOR_REJECT_NOT_APPROVED_VOUCHERS_REQUEST =
  "AUDITOR_REJECT_NOT_APPROVED_VOUCHERS_REQUEST";
export const AUDITOR_REJECT_NOT_APPROVED_VOUCHERS_SUCCESS =
  "AUDITOR_REJECT_NOT_APPROVED_VOUCHERS_SUCCESS";
export const AUDITOR_REJECT_NOT_APPROVED_VOUCHERS_FAIL =
  "AUDITOR_REJECT_NOT_APPROVED_VOUCHERS_FAIL";
export const AUDITOR_REJECT_NOT_APPROVED_VOUCHERS_RESET =
  "AUDITOR_REJECT_NOT_APPROVED_VOUCHERS_RESET";

export const CEO_REJECT_PRE_APPROVED_VOUCHERS_REQUEST =
  "CEO_REJECT_PRE_APPROVED_VOUCHERS_REQUEST";
export const CEO_REJECT_PRE_APPROVED_VOUCHERS_SUCCESS =
  "CEO_REJECT_PRE_APPROVED_VOUCHERS_SUCCESS";
export const CEO_REJECT_PRE_APPROVED_VOUCHERS_FAIL =
  "CEO_REJECT_PRE_APPROVED_VOUCHERS_FAIL";
export const CEO_REJECT_PRE_APPROVED_VOUCHERS_RESET =
  "CEO_REJECT_PRE_APPROVED_VOUCHERS_RESET";

export const ACCOUNTANT_DELETE_VOUCHER_BY_ID_REQUEST =
  "ACCOUNTANT_DELETE_VOUCHER_BY_ID_REQUEST";
export const ACCOUNTANT_DELETE_VOUCHER_BY_ID_SUCCESS =
  "ACCOUNTANT_DELETE_VOUCHER_BY_ID_SUCCESS";
export const ACCOUNTANT_DELETE_VOUCHER_BY_ID_FAIL =
  "ACCOUNTANT_DELETE_VOUCHER_BY_ID_FAIL";
export const ACCOUNTANT_DELETE_VOUCHER_BY_ID_RESET =
  "ACCOUNTANT_DELETE_VOUCHER_BY_ID_RESET";

export const ACCOUNTANT_DELETE_BULK_VOUCHERS_REQUEST =
  "ACCOUNTANT_DELETE_BULK_VOUCHERS_REQUEST";
export const ACCOUNTANT_DELETE_BULK_VOUCHERS_SUCCESS =
  "ACCOUNTANT_DELETE_BULK_VOUCHERS_SUCCESS";
export const ACCOUNTANT_DELETE_BULK_VOUCHERS_FAIL =
  "ACCOUNTANT_DELETE_BULK_VOUCHERS_FAIL";
export const ACCOUNTANT_DELETE_BULK_VOUCHERS_RESET =
  "ACCOUNTANT_DELETE_BULK_VOUCHERS_RESET";
